program: main.py
method: grid
metric: 
  goal: maximize
  name: accuracy
parameters:
  hidden_sz:
    values: [64, 128, 256] 
  markov_iter:
    values: [200, 300]
  gibbs_samples:
    values: [10, 20, 30]
  rbm_epoch:
    values: [1, 3, 5, 7]
early_terminate:
  type: hyperband
  s: 2
  eta: 3
  max_iter: 27